### ISSUE TITLE
Image comparison

### ISSUE THREAD

**Issue by wvxwxvw** [WinMerge/winimerge#24]
Much does not fit. Stretch fields please.
![2021 09 11_034138](https://user-images.githubusercontent.com/13194155/132930904-ea4b65da-908a-41dc-bef0-06099c1c8d91.png)
And what is "CD Threshold"? CD - how is it deciphered?

**Comment by sdottaka** [comment]
Fixed with commit 7b751b2342e2bb2924df53e13b93c92a21d35632

Thank you for the report.
