### ISSUE TITLE
Support 16-bit images

### ISSUE THREAD

**Issue by kmilos** [WinMerge/winimerge#6]
Currently WinMerge 2.16.4 displays 16-bit grayscale PNGs as two incorrectly rendered half-planes next to each other, and the app crashes if e.g. CD threshold is changed in large steps. I haven't tried color (48-bit) images.

FreeImage already has support for reading 16-bit per channel (PNG, TIFF, PGM/PPM, and others), so I presume most of this is internal to WinIMerge.

Even a correct conversion to 8/24/32-bit from 16/48/64-bit would be a good start.

**Comment by sdottaka** [comment]
I tried using the image below, but couldn't reproduce this bug.
Could you attach an image file that can be reproduced?

http://www.yafaray.org/community/forum/viewtopic.php?f=22&t=3115

**Comment by kmilos** [comment]
Ok, that example is 48-bit RGB actually, and it does work! And so does 64-bit RGBA it seems.

Real single channel grayscale 16-bit does not, try e.g. the one here: https://github.com/python-pillow/Pillow/issues/3011#issue-298775120

**Comment by sdottaka** [comment]
Thank you for the information.
Now I can reproduce this bug using the image above.
I will try to fix the bug.

**Comment by kmilos** [comment]
Many thanks for the fix, 1.0.15.0 dll is working for me now on 16-bit grayscale images (tried PNG, PGM and TIFF).

**Comment by sdottaka** [comment]
Thank you for confirmation.

Note that 16-bit grayscale images are converted to 8-bit grayscale before comparison.

**Comment by kmilos** [comment]
Btw, I'm not 100% sure about the the conversion after I looked into the FreeImage docs - it seems convertToType() will behave differently for the grayscale UINT16 (scaling which is image content dependent), while RGB16/RGBA16 will always be divided by 256 in convertTo32Bits(). I suggest using convertTo8Bits() instead to make the conversion consistent.
